PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX parking: <https://github.com/luposdate3000/parking#>

SELECT (count(?spot) as ?numberOfFreeSpaces)
WHERE {
  ?o a parking:Observation ;
  parking:spotInArea ?spot ;
  parking:area 1 ;
  parking:isOccupied "false"^^xsd:boolean ;
  parking:resultTime ?lastObservedAt .
  {
    SELECT(MAX(?d) AS ?lastObservedAt) ?spot WHERE{
      ?o2 a parking:Observation ;
      parking:spotInArea ?spot ;
      parking:area 1 ;
      parking:resultTime ?d .
    }
    GROUP BY ?spot
  }
}
