select ?n where { 
	?a <hasGivenName> ?n. 
	?a <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> "actor". 
	?a <livesIn> ?city. 
	?a <actedIn> ?m1. 
	?m1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> "movie". 
}
