select distinct ?n1 ?n2 where { 
	?p1 <hasFamilyName> ?n1. 
	?p2 <hasFamilyName> ?n2. 
	?scientist <http://www.w3.org/2000/01/rdf-schema#label> "scientist"
	?p1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?scientist. 
	?p1 ?unused1 ?city. 
	?p2 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?scientist. 
	?p2 ?unused2 ?city. 
	filter (?p1 != ?p2). 
}
