src/commonMain/kotlin/lupos/JenaRequest.kt
src/commonMain/kotlin/lupos/SparqlTestSuite.kt
src/commonMain/kotlin/lupos/s00misc/EOperatorID.kt
src/commonMain/kotlin/lupos/s00misc/XMLElement.kt
src/commonMain/kotlin/lupos/s00misc/XMLElementFromXml.kt
src/commonMain/kotlin/lupos/s01io/buffer/Benchmark.kt
src/commonMain/kotlin/lupos/s02buildSyntaxTree/Runtime.kt
src/commonMain/kotlin/lupos/s02buildSyntaxTree/sparql1_1/SPARQLParser.kt
src/commonMain/kotlin/lupos/s02buildSyntaxTree/sparql1_1/SPARQLScanner.kt
src/commonMain/kotlin/lupos/s02buildSyntaxTree/turtle/TurtleParser.kt
src/commonMain/kotlin/lupos/s02buildSyntaxTree/turtle/TurtleParserWithDictionary.kt
src/commonMain/kotlin/lupos/s02buildSyntaxTree/turtle/TurtleParserWithStringTriples.kt
src/commonMain/kotlin/lupos/s02buildSyntaxTree/turtle/TurtleScanner.kt
src/commonMain/kotlin/lupos/s04arithmetikOperators/singleinput/AOPBuildInCallDATATYPE.kt
src/commonMain/kotlin/lupos/s04logicalOperators/OPBase.kt
src/commonMain/kotlin/lupos/s04logicalOperators/iterator/ColumnIterator.kt
src/commonMain/kotlin/lupos/s04logicalOperators/noinput/LOPTriple.kt
src/commonMain/kotlin/lupos/s04logicalOperators/singleinput/LOPFilter.kt
src/commonMain/kotlin/lupos/s04logicalOperators/singleinput/LOPGroup.kt
src/commonMain/kotlin/lupos/s05tripleStore/TripleStore.kt
src/commonMain/kotlin/lupos/s06buildOperatorGraph/OperatorGraphVisitor.kt
src/commonMain/kotlin/lupos/s08logicalOptimisation/LogicalOptimizerArithmetic.kt
src/commonMain/kotlin/lupos/s08logicalOptimisation/LogicalOptimizerJoinOrder.kt
src/commonMain/kotlin/lupos/s08logicalOptimisation/OptimizerBase.kt
src/commonMain/kotlin/lupos/s08logicalOptimisation/OptimizerCompoundBase.kt
src/commonMain/kotlin/lupos/s09physicalOperators/multiinput/POPJoinHashMap.kt
src/commonMain/kotlin/lupos/s09physicalOperators/noinput/POPGraphOperation.kt
src/commonMain/kotlin/lupos/s09physicalOperators/noinput/POPModifyData.kt
src/commonMain/kotlin/lupos/s09physicalOperators/noinput/POPValuesImportXML.kt
src/commonMain/kotlin/lupos/s09physicalOperators/singleinput/POPGroup.kt
src/commonMain/kotlin/lupos/s09physicalOperators/singleinput/POPModify.kt
src/commonMain/kotlin/lupos/s10physicalOptimisation/PhysicalOptimizerNaive.kt
src/commonMain/kotlin/lupos/s10physicalOptimisation/PhysicalOptimizerTripleIndex.kt
src/commonMain/kotlin/lupos/s14endpoint/Endpoint.kt
src/commonMain/kotlin/lupos/s14endpoint/EndpointServer.kt
src/commonMain/kotlin/lupos/s14endpoint/XMLElementToOPBase.kt
src/commonS00LaunchBinaryTestsMain/kotlin/Main.kt
src/commonS00LaunchEndpointMain/kotlin/Main.kt
src/commonS00ResultFlowExecuteTestsMain/kotlin/lupos/s00misc/BinaryTestHelper.kt
src/commonS00SanityChecksOffMain/kotlin/lupos/s00misc/SanityCheck.kt
src/commonS00SanityChecksOnMain/kotlin/lupos/s00misc/SanityCheck.kt
src/commonS00TraceOnMain/kotlin/lupos/s00misc/Trace.kt
src/commonS01BufferDiskbasedMain/kotlin/lupos/s01io/buffer/Cache.kt
src/commonS01BufferMainmemoryMain/kotlin/lupos/s01io/buffer/BufferManager.kt
src/commonS05HashMapMain/kotlin/lupos/s05tripleStore/TripleStore.kt
src/commonS12DummyMain/kotlin/lupos/s12p2p/P2P.kt
src/commonS14ClientKtorMain/kotlin/lupos/s14endpoint/EndpointClientImpl.kt
src/commonS15LocalMain/kotlin/lupos/s15tripleStoreDistributed/DistributedTripleStore.kt
src/commonTestBak/kotlin/commonTest/BPlusTreeTests.kt
src/jvmMain/kotlin/lupos/datastructures/b_plus_tree/B_Plus_Tree.kt
src/jvmMain/kotlin/lupos/datastructures/b_plus_tree/B_Plus_Tree_Int_to_Int.kt
src/jvmMain/kotlin/lupos/datastructures/lsm_tree/LSM_Tree.kt
src/jvmMain/kotlin/lupos/datastructures/radix_tree/Radix_Tree.kt
src/jvmS00LaunchJavaFuzzMain/kotlin/Main.kt
src/jvmS00LaunchWarnkeFuzzMain/kotlin/Main.kt
src/jvmS01BufferMemoryMappedMain/kotlin/lupos/s01io/buffer/MappedByteBufferPage.kt
src/jvmS01BufferMemoryMappedUnsafeMain/kotlin/lupos/s01io/buffer/CachedFile.kt
src/jvmS01BufferUnsafeHelperMain/kotlin/lupos/s01io/buffer/UnsafePage.kt
src/jvmS14ServerKorioMain/kotlin/lupos/s14endpoint/EndpointServerImpl.kt
src/linuxX64Main/kotlin/lupos/s00misc/Lock.kt
src/linuxX64Main/kotlin/lupos/s00misc/ReadWriteLock.kt
src/macosX64Main/kotlin/lupos/s00misc/Lock.kt
src/macosX64Main/kotlin/lupos/s00misc/ReadWriteLock.kt
