src/commonMain/kotlin/lupos/SparqlTestSuite.kt
src/commonMain/kotlin/lupos/s00misc/XMLElement.kt
src/commonMain/kotlin/lupos/s00misc/XMLElementFromXml.kt
src/commonMain/kotlin/lupos/s04logicalOperators/iterator/ColumnIterator.kt
src/commonMain/kotlin/lupos/s05tripleStore/TripleStore.kt
src/commonMain/kotlin/lupos/s06buildOperatorGraph/OperatorGraphVisitor.kt
src/commonMain/kotlin/lupos/s08logicalOptimisation/OptimizerBase.kt
src/commonMain/kotlin/lupos/s08logicalOptimisation/OptimizerCompoundBase.kt
src/commonMain/kotlin/lupos/s09physicalOperators/multiinput/POPJoinHashMap.kt
src/commonMain/kotlin/lupos/s14endpoint/XMLElementToOPBase.kt
src/commonS00SanityChecksOffMain/kotlin/lupos/s00misc/SanityCheck.kt
src/commonS00SanityChecksOnMain/kotlin/lupos/s00misc/SanityCheck.kt
src/commonS15DistributedMain/kotlin/lupos/s15tripleStoreDistributed/DistributedTripleStore.kt
src/jvmS14ServerKorioMain/kotlin/lupos/s14endpoint/EndpointServerImpl.kt
