/* this File is autogenerated by generate-buildfile.kts */
/* DO NOT MODIFY DIRECTLY */
package lupos.s04logicalOperators.iterator
typealias ColumnIteratorDebug = ColumnIteratorDebugCount
typealias RowIteratorDebug = RowIteratorDebugVerbose
const val MERGE_SORT_MIN_ROWS = 8
