package lupos.s04logicalOperators.iterator

import lupos.s00misc.Coverage

/* this File is autogenerated by generate-buildfile.kts */
/* DO NOT MODIFY DIRECTLY */
typealias ColumnIteratorDebug = ColumnIteratorDebugFast
