# all drivers having the correct licences of at least one car they drive
# should be :Alfred, :Herbert and :Tom
PREFIX : <http://www.ifis.uni-luebeck.de/ontologies/europeanDrivingLicences#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT DISTINCT ?driver WHERE {
 ?driver :drives ?vehicle.
 ?vehicle :requiresLicenceForDriving ?licence.
 ?driver :hasLicence ?licenceInstance.
 ?licenceInstance rdf:type ?licence.
}