# Tom belongs to the class :PersonWithLicence
PREFIX : <http://www.ifis.uni-luebeck.de/ontologies/europeanDrivingLicences#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
ASK {
 :Tom rdf:type :PersonWithLicence.
}