PREFIX bench: <http://localhost/vocabulary/bench/> 
PREFIX dc: <http://purl.org/dc/elements/1.1/> 
PREFIX dcterms: <http://purl.org/dc/terms/> 
PREFIX foaf: <http://xmlns.com/foaf/0.1/> 
PREFIX person: <http://localhost/persons/> 
PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX swrc: <http://swrc.ontoware.org/ontology#> 
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#> 

SELECT * {
    ?x swrc:month ?o0 .
    ?x foaf:homepage ?o1 .
    ?x dc:title ?o2 .
    ?x rdf:type ?o3 .
}
