package lupos.s00misc

/* this File is autogenerated by generate-buildfile.kts */
/* DO NOT MODIFY DIRECTLY */
typealias MySetAny<T> = MySetAnyBinary<T>

typealias MySetLong = MySetLongBinary
typealias MySetInt = MySetIntBinary
typealias MyMapInt<T> = MyMapIntBinaryTree<T>
typealias MyMapLong<T> = MyMapLongBinaryTree<T>
typealias MyMapLongInt = MyMapLongIntBinaryTree
typealias MyMapIntInt = MyMapIntIntBinaryTree
