/* this File is autogenerated by generate-buildfile.kts */
/* DO NOT MODIFY DIRECTLY */
package lupos.s00misc
typealias MySetGeneric<T> = MySetGenericBTree<T>
typealias MySetLong = MySetLongBTree
typealias MySetInt = MySetIntBTree
typealias MySetDouble = MySetDoubleBTree
typealias MyMapIntGeneric<T> = MyMapIntGenericBTree<T>
typealias MyMapLongGeneric<T> = MyMapLongGenericBTree<T>
typealias MyMapLongInt = MyMapLongIntBTree
typealias MyMapIntInt = MyMapIntIntBTree
typealias MyMapDoubleInt = MyMapDoubleIntBTree
