/* this File is autogenerated by generate-buildfile.kts */
/* DO NOT MODIFY DIRECTLY */
package lupos.s00misc

/* Substitutions :: Long */
class MyListLong {
    @JvmField
    var size = 0
    @JvmField
    var capacity = 10
    @JvmField
    var data: LongArray

    inline fun reserve(capacity: Int) {
        if (this.capacity < capacity) {
            this.capacity = capacity
            val tmp = LongArray(capacity)
            data.copyInto(tmp)
            data = tmp
        }
    }

    constructor() {
        data = LongArray(capacity)
    }

    constructor(value: Long) {
        data = LongArray(capacity)
        data[size++] = value
    }

    constructor(initialCapacity: Int, init: (Int) -> Long) {
        capacity = initialCapacity
        size = capacity
        data = LongArray(capacity) { init(it) }
    }

    fun clear() {
        size = 0
    }

    fun add(value: Long) {
        if (size + 1 >= capacity) {
            reserve(capacity * 2)
        }
        data[size++] = value
    }

    inline operator fun get(idx: Int) = data.get(idx)
    inline operator fun set(idx: Int, key: Long) = data.set(idx, key)
    fun removeAt(idx: Int): Long {
        val res = data[idx]
        require(idx < size)
        for (i in idx until size) {
            data[i] = data[i + 1]
        }
        size--
        return res
    }

    fun add(idx: Int, value: Long) {
        if (size + 1 >= capacity) {
            reserve(capacity * 2)
        }
        if (idx < size) {
            size++
            for (i in size downTo idx + 1) {
                data[i] = data[i - 1]
            }
            data[idx] = value
        } else {
            data[size++] = value
        }
    }

    inline operator fun iterator() = MyListLongIterator(this)
    class MyListLongIterator(@JvmField val data: MyListLong) : Iterator<Long> {
        var index = 0
        override fun hasNext() = index < data.size
        override fun next() = data.data[index++]
    }
}
