/* this File is autogenerated by generate-buildfile.kts */
/* DO NOT MODIFY DIRECTLY */
package lupos.s00misc

import lupos.s00misc.Coverage

/* Substitutions :: Long,,,LongArray, */
class MyListLong {
    class MyListLongPage() {
        var next: MyListLongPage? = null
        var size = 0/*local*/
        val data: LongArray = LongArray(5) 
    }

    var pagecount = 1
    @JvmField
    var size = 0
    @JvmField
    var page = MyListLongPage()
    @JvmField
    var lastpage = page

    fun shrinkToFit() {
        if (pagecount > 5) {
            var capacity = pagecount * page.data.size
            if (capacity > size * 2) {
                var c = 1
                val b = MyListLongPage()
                var t = b
                var it = iterator()
                while (it.hasNext()) {
                    var j = 0
                    while (it.hasNext() && j < t.data.size) {
                        t.data[j++] = it.next()
                    }
                    t.size = j
                    if (it.hasNext()) {
                        t.next = MyListLongPage()
                        t = t.next!!
                        c++
                    }
                }
                pagecount = c
                page = b
                lastpage = t
            }
        }
    }

    inline fun reserve(capacity: Int) {
    }

    constructor() {
    }

    constructor(value: Long) {
        size = 1
        page.size = 1
        page.data[0] = value
    }

    constructor(initialCapacity: Int, init: (Int) -> Long) {
        size = initialCapacity
        var i = 0
        var tmp = page
        while (i < size) {
            var j = tmp.size
            while (tmp.size < tmp.data.size && i < size) {
                tmp.data[j++] = init(i++)
            }
            tmp.size = j
            if (i < size) {
                val p = MyListLongPage()
                pagecount++
                p.next = tmp.next
                tmp.next = p
                tmp = p
            }
        }
        lastpage = tmp
    }

    fun clear() {
        size = 0
        page = MyListLongPage()
        pagecount = 1
        lastpage = page
    }

    fun add(value: Long) {
        if (lastpage.size < lastpage.data.size) {
            lastpage.data[lastpage.size++] = value
        } else {
            lastpage.next = MyListLongPage()
            pagecount++
            lastpage = lastpage.next!!
            lastpage.data[lastpage.size++] = value
        }
        size++
        shrinkToFit()
    }

    inline operator fun get(idx: Int): Long {
        require(idx < size)
        var tmp = page
        var offset = 0
        while (offset + tmp.size <= idx) {
            offset += tmp.size
            require(tmp.next != null) { debug() + " $offset $idx" }
            tmp = tmp.next!!
        }
        return tmp.data[idx - offset] as Long
    }

    fun remove(value: Long): Boolean {
        var i = 0
        var tmp: MyListLongPage? = page
        while (i < size) {
            var j = 0
            while (j < tmp!!.size) {
                if (tmp!!.data[j] == value) {
                    while (j < tmp!!.size - 1) {
                        tmp.data[j] = tmp.data[j + 1]
                        j++
                    }
                    tmp.size--
                    size--
                    return true
                }
                j++
                i++
            }
            tmp = tmp.next
        }
        return false
    }

    fun removeAt(idx: Int): Long {
        var tmp = page
        var offset = 0
        while (offset + tmp.size < idx) {
            offset += tmp.size
            tmp = tmp.next!!
        }
        var i = idx - offset
        var res = tmp.data[i] as Long
        while (i < tmp.size - 1) {
            tmp.data[i] = tmp.data[i + 1]
            i++
        }
        tmp.size--
        size--
        return res
    }

    inline operator fun set(idx: Int, value: Long) {
        require(idx <= size)
        if (idx == size) {
            if (lastpage.size < lastpage.data.size) {
                lastpage.data[lastpage.size] = value
                lastpage.size++
            } else {
                lastpage.next = MyListLongPage()
                pagecount++
                lastpage = lastpage.next!!
                lastpage.size = 1
                lastpage.data[0] = value
            }
            size++
        } else {
            var tmp = page
            var offset = 0
            var t = idx
            while (t >= tmp.size) {
                offset += tmp.size
                t = idx - offset
                tmp = tmp.next!!
            }
            tmp.data[t] = value
        }
        shrinkToFit()
    }

    fun add(idx: Int, value: Long) {
        require(idx <= size)
        if (idx == size) {
            if (lastpage.size < lastpage.data.size) {
                lastpage.data[lastpage.size++] = value
            } else {
                lastpage.next = MyListLongPage()
                pagecount++
                lastpage = lastpage.next!!
                lastpage.data[lastpage.size++] = value
            }
        } else {
            var tmp = page
            var offset = 0
            var t = idx
            while (t > tmp.size) {
                offset += tmp.size
                t = idx - offset
                tmp = tmp.next!!
            }
            if (t == tmp.size && tmp.size < tmp.data.size) {
                tmp.data[t] = value
                tmp.size++
            } else {
                if (t == tmp.size) {
                    offset += tmp.size
                    t = idx - offset
                    tmp = tmp.next!!
                }
                if (tmp.size < tmp.data.size) {
                    for (i in tmp.size downTo t + 1) {
                        tmp.data[i] = tmp.data[i - 1]
                    }
                    tmp.data[t] = value
                    tmp.size++
                } else {
                    var p = MyListLongPage()
                    pagecount++
                    p.next = tmp.next
                    tmp.next = p
                    var j = 0
                    for (i in t until tmp.data.size) {
                        p.data[j++] = tmp.data[i]
                    }
                    tmp.size = t + 1
                    p.size = j
                    tmp.data[t] = value
                    if (lastpage == tmp) {
                        lastpage = p
                    }
                }
            }
        }
        size++
        shrinkToFit()
    }

    fun debug(): String {
        var res = StringBuilder()
        var totalsize = 0
        res.append("Long debug $size [")
        var tmp = page
        while (true) {
            totalsize += tmp.size
            res.append("" + tmp.size + "{")
            for (i in 0 until tmp.size) {
                res.append("" + tmp.data[i] + ", ")
            }
            res.append("}, ")
            if (tmp.next == null) {
                break
            }
            tmp = tmp.next!!
        }
        res.append("]")
        require(totalsize == size, { "size incorrect ${res.toString()}" })
        require(tmp == lastpage, { "lastpage incorrect ${res.toString()}" })
        return res.toString()
    }

    inline operator fun iterator() = MyListLongIterator(this)
    class MyListLongIterator(@JvmField val data: MyListLong) : Iterator<Long> {
        var tmp = data.page
        var globalidx = 0
        var idx = 0
        override fun hasNext() = idx < tmp.size || tmp.next != null
        override fun next(): Long {
            if (idx == tmp.size) {
                globalidx += idx
                tmp = tmp.next!!
                idx = 0
            }
            return tmp.data[idx++] as Long
        }
    }
}
