package lupos.s00misc
import lupos.s00misc.Coverage
/* this File is autogenerated by generate-buildfile.kts */
/* DO NOT MODIFY DIRECTLY */


/* Substitutions :: GenericK,GenericV,<GenericK : Comparable<GenericK>, GenericV>,<GenericK, GenericV>,<GenericK>,<GenericV>,Generic,Generic */
class MyMapGenericGenericBinaryTree<GenericK : Comparable<GenericK>, GenericV>() {
    @JvmField
    var keys = MySetGenericBinaryTree<GenericK>()
    @JvmField
    var values = MyListGeneric<GenericV>()
    var size: Int = 0
        get() = keys.size

    inline fun reserve(capacity: Int) {
        keys.reserve(capacity)
        values.reserve(capacity)
    }

    constructor(data: Pair<GenericK, GenericV>) : this() {
        set(data.first, data.second)
    }

    inline operator fun get(key: GenericK): GenericV? {
        var res: GenericV? = null
        keys.find(key, { res = values[it] })
        return res
    }

    inline operator fun set(key: GenericK, value: GenericV) {
        keys.add(key, { values.add(it, value) }, { values[it] = value })
    }

    inline fun getOrCreate(key: GenericK, crossinline onCreate: () -> GenericV): GenericV {
        var value: GenericV? = null
        keys.add(key, {
            value = onCreate()
            values.add(it, value!!)
        }, {
            value = values[it]
        })
        return value!!
    }

    fun withFastInitializer(action: (MyMapGenericGenericBinaryTree<GenericK, GenericV>) -> Unit) = action(this)
    fun appendAssumeSorted(key: GenericK, value: GenericV): GenericV {
        keys.add(key)
        values.add(value)
        return value
    }

    fun clear() {
        keys.clear()
        values.clear()
    }

    inline fun iterator() = MyMapGenericGenericBinaryTreeIterator(this)
    inline fun forEach(crossinline action: (GenericK, GenericV) -> Unit) {
        val iteratorK = keys.iterator()
        val iteratorV = values.iterator()
        while (iteratorK.hasNext()) {
            val k = iteratorK.next()
            val v = iteratorV.next()
            action(k, v)
        }
    }

    class MyMapGenericGenericBinaryTreeIterator<GenericK : Comparable<GenericK>, GenericV>(val data: MyMapGenericGenericBinaryTree<GenericK, GenericV>) {
        var index = 0
        fun hasNext() = index < data.values.size
        fun next() = data.keys.data[index++]
        fun value() = data.values[index - 1]
    }

    fun safeToFile(filename: String) {
        throw Exception("not Implemented")
    }
}
