/* this File is autogenerated by generate-buildfile.kts */

/* DO NOT MODIFY DIRECTLY */

/* to Substitute:: Double,UInt */
package lupos.s00misc

import lupos.s00misc.Coverage

class MyMapDoubleUIntBinaryTree() {
    @JvmField
    var keys = MySetDouble()
    @JvmField
    var values = MyListUInt()
    var size: Int = 0
        get() = keys.size

    constructor(data: Pair<Double, UInt>) : this() {
        set(data.first, data.second)
    }

    inline operator fun get(key: Double): UInt? {
        var res: UInt? = null
        keys.find(key, { res = values[it] })
        return res
    }

    inline operator fun set(key: Double, value: UInt) {
        keys.add(key, { values.add(it, value) }, { values[it] = value })
    }

    inline fun getOrCreate(key: Double, crossinline onCreate: () -> UInt): UInt {
        var value: UInt? = null
        keys.add(key, {
            value = onCreate()
            values.add(it, value!!)
        }, {
            value = values[it]
        })
        return value!!
    }

    fun appendAssumeSorted(key: Double, value: UInt): UInt {
        keys.add(key)
        values.add(value)
        return value
    }

    fun clear() {
        keys.clear()
        values.clear()
    }

    inline fun iterator() = MyMapDoubleUIntBinaryTreeIterator(this)
    class MyMapDoubleUIntBinaryTreeIterator(val data: MyMapDoubleUIntBinaryTree) {
        var index = 0
        fun hasNext() = index < data.values.size
        fun next() = data.keys.data[index++]
        fun value() = data.values[index - 1]
    }

    fun safeToFile(filename: String) {
        File(filename).dataOutputStream { out ->
            out.writeInt(size)
            for (i in 0 until size) {
                out.writeDouble(keys.data[i])
            }
            for (i in 0 until size) {
                out.writeUInt(values[i])
            }
        }
    }

    fun readFromFile(filename: String) {
        File(filename).dataInputStream { fis ->
            var size = fis.readInt()
            for (i in 0 until size) {
                keys.appendAssumeSorted(fis.readDouble())
            }
            for (i in 0 until size) {
                values.add(fis.readUInt())
            }
        }
    }
}
