  prefix bsbm: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/> 

  SELECT ?otherProduct ?sameFeatures
  {
    ?otherProduct a bsbm:Product .
    FILTER(?otherProduct != bsbm-inst:ProductFeature47 rdf:type bsbm:ProductFeature .)
    {
      SELECT ?otherProduct (count(?otherFeature) As ?sameFeatures)
      {
        bsbm-inst:ProductFeature47 rdf:type bsbm:ProductFeature . bsbm:productFeature ?feature .
        ?otherProduct bsbm:productFeature ?otherFeature .
        FILTER(?feature=?otherFeature)
      }
      Group By ?otherProduct
    }
  }
  Order By desc(?sameFeatures) ?otherProduct
  Limit 10
