PREFIX bsbm-inst: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/>
PREFIX bsbm: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>

SELECT ?label ?comment ?producer ?productFeature ?propertyTextual1 ?propertyTextual2 ?propertyTextual3
 ?propertyNumeric1 ?propertyNumeric2 ?propertyTextual4 ?propertyTextual5 ?propertyNumeric4 
WHERE {
    bsbm-inst:ProductFeature15 rdf:type bsbm:ProductFeature . rdfs:label ?label .
    bsbm-inst:ProductFeature15 rdf:type bsbm:ProductFeature . rdfs:comment ?comment .
    bsbm-inst:ProductFeature15 rdf:type bsbm:ProductFeature . bsbm:producer ?p .
    ?p rdfs:label ?producer .
    bsbm-inst:ProductFeature15 rdf:type bsbm:ProductFeature . dc:publisher ?p . 
    bsbm-inst:ProductFeature15 rdf:type bsbm:ProductFeature . bsbm:productFeature ?f .
    ?f rdfs:label ?productFeature .
    bsbm-inst:ProductFeature15 rdf:type bsbm:ProductFeature . bsbm:productPropertyTextual1 ?propertyTextual1 .
    bsbm-inst:ProductFeature15 rdf:type bsbm:ProductFeature . bsbm:productPropertyTextual2 ?propertyTextual2 .
    bsbm-inst:ProductFeature15 rdf:type bsbm:ProductFeature . bsbm:productPropertyTextual3 ?propertyTextual3 .
    bsbm-inst:ProductFeature15 rdf:type bsbm:ProductFeature . bsbm:productPropertyNumeric1 ?propertyNumeric1 .
    bsbm-inst:ProductFeature15 rdf:type bsbm:ProductFeature . bsbm:productPropertyNumeric2 ?propertyNumeric2 .
    OPTIONAL { bsbm-inst:ProductFeature15 rdf:type bsbm:ProductFeature . bsbm:productPropertyTextual4 ?propertyTextual4 }
    OPTIONAL { bsbm-inst:ProductFeature15 rdf:type bsbm:ProductFeature . bsbm:productPropertyTextual5 ?propertyTextual5 }
    OPTIONAL { bsbm-inst:ProductFeature15 rdf:type bsbm:ProductFeature . bsbm:productPropertyNumeric4 ?propertyNumeric4 }
}
