PREFIX dbpprop:	<http://dbpedia.org/property/>
PREFIX dbpedia:	<http://dbpedia.org/resource/>

SELECT * 
WHERE {
 {
   ?s ?p dbpedia:L%C3%BCbeck .
   ?s ?p dbpedia:Berlin .
 } UNION {
   dbpedia:L%C3%BCbeck ?p ?o .
   dbpedia:Berlin ?p ?o .
 }
}