PREFIX dbpprop:	<http://dbpedia.org/property/>
PREFIX dbpedia:	<http://dbpedia.org/resource/>

SELECT * 
WHERE {
 dbpedia:L%C3%BCbeck ?p ?o .
 FILTER(
   ?p = dbpprop:north ||
   ?p = dbpprop:northwest ||
   ?p = dbpprop:west ||
   ?p = dbpprop:southwest ||
   ?p = dbpprop:south ||
   ?p = dbpprop:southeast ||
   ?p = dbpprop:east ||
   ?p = dbpprop:northeast
       )
}