# all drivers, where a required licence is missing 
# should be :Herbert
PREFIX : <http://www.ifis.uni-luebeck.de/ontologies/europeanDrivingLicences#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT DISTINCT ?driver WHERE {
 ?driver :hasLicence ?licenceInstance.
 ?licenceInstance rdf:type ?licence.
 ?licence :requiresLicence ?requiredLicence.
 FILTER NOT EXISTS {
	?driver :hasLicence ?licenceInstanceOfRequiredLicence.
	?licenceInstanceOfRequiredLicence rdf:type ?requiredLicence.
 }
}