# all drivers having no licence of at least one car they drive
# should be :Tom
PREFIX : <http://www.ifis.uni-luebeck.de/ontologies/europeanDrivingLicences#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT ?driver WHERE {
 ?driver :drives ?vehicle.
 ?vehicle :requiresLicenceForDriving ?licence.
 FILTER NOT EXISTS { 
   ?driver :hasLicence ?licenceInstance.
   ?licenceInstance rdf:type ?licence.
 }
}