package lupos.s16network

/* this File is autogenerated by generate-buildfile.kts */
/* DO NOT MODIFY DIRECTLY */
const val NETWORK_PACKET_SIZE = 8196
const val NETWORK_PACKET_MIN_TRIPLES = 128
const val NETWORK_DEFAULT_PORT = 2323
