PREFIX dc: <http://purl.org/dc/elements/1.1/> 
PREFIX dcterms: <http://purl.org/dc/terms/> 
PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX swrc: <http://swrc.ontoware.org/ontology#> 
PREFIX foaf: <http://xmlns.com/foaf/0.1/> 
PREFIX bench: <http://localhost/vocabulary/bench/> 
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#> 
PREFIX person: <http://localhost/persons/> 

SELECT * {
    ?x foaf:homepage ?o0 .
    ?x swrc:editor ?o1 .
    ?x swrc:volume ?o2 .
}
