package lupos.s00misc
/* explicitly storing the classname has the advantage, that the classname is accessible in native code too, and not just via reflection */
abstract public class Luposdate3000Exception(internal val classname: String, msg: String) : Exception(msg)
// not implemented exceptions --->>>
open public class NotImplementedException(classname: String, msg: String) : Luposdate3000Exception(classname, msg)
public class HistogramNotImplementedException(classname: String) : NotImplementedException("HistogramNotImplementedException", "Histograms not implemented in '$classname'.")
public class IteratorBundleColumnModeNotImplementedException : NotImplementedException("IteratorBundleColumnModeNotImplementedException", "IteratorBundle is unable to convert to column Mode.")
public class IteratorBundleRowModeNotImplementedException : NotImplementedException("IteratorBundleRowModeNotImplementedException", "IteratorBundle is unable to convert to row Mode.")
public class SparqlFeatureNotImplementedException(name: String) : NotImplementedException("SparqlFeatureNotImplementedException", "Sparql feature '$name' not implemented.")
public class EvaluateNotImplementedException(classname: String) : NotImplementedException("EvaluateNotImplementedException", "Evaluate not implemented in '$classname'.")
public class ToSparqlNotImplementedException(classname: String) : NotImplementedException("ToSparqlNotImplementedException", "toSparql not implemented in '$classname'.")
public class GraphVariablesNotImplementedException(classname: String) : NotImplementedException("GraphVariablesNotImplementedException", "variables at graph-name position are currently not implemented")
public class UnknownManifestException(classname: String, msg: String) : NotImplementedException("UnknownManifestException", "$classname :: $msg")
public class DirectoryCompareNotImplementedException : NotImplementedException("DirectoryCompareNotImplementedException", "Comparing directories is not implemented")
public class GraphVarHistogramsNotImplementedException : NotImplementedException("GraphVarHistogramsNotImplementedException", "histograms for triples using graph variable not implemented.")
public class TriplePatternsContainingTheSameVariableTwiceNotImplementedException : NotImplementedException("TriplePatternsContainingTheSameVariableTwiceNotImplementedException", "triple pattern currently must not contain the same variable twice.")
// syntax exceptions --->>>
abstract public class SyntaxException(classname: String, msg: String) : Luposdate3000Exception(classname, msg)
public class RecoursiveVariableDefinitionSyntaxException(name: String) : SyntaxException("RecoursiveVariableDefinitionSyntaxException", "Recoursive variable definition not allowed '$name'.")
public class ProjectionDoubleDefinitionOfVariableSyntaxException(name: String) : SyntaxException("DoubleDefinitionOfVariableSyntaxException", "Projection must not contain same variable as bind and selection '$name'.")
public class AggregateNotAllowedSyntaxException : SyntaxException("AggregateNotAllowedSyntaxException", "Aggregates are not allowed here.")
public class VariableNotDefinedSyntaxException(classname: String, name: String) : SyntaxException("VariableNotDefinedSyntaxException", "Variable '$name' unknown within '$classname'.")
public class GroupByClauseNotUsedException : SyntaxException("GroupByClauseNotUsedException", "expression within group-by-clauses must be bound to a variable.")
public class GroupByColumnMissing(name: String) : SyntaxException("GroupByColumnMissing", "Group By requires the column '$name', which does not exist within this GroupBy-Clause.")
public class GroupByDuplicateColumnException : SyntaxException("GroupByDuplicateColumnException", "no duplicate columns allowed in group-by.")
public class XMLNotParseableException : SyntaxException("XMLNotParseableException", "Xml is not parseable.")
// evaluation exceptions --->>>
abstract public class EvaluationException(classname: String, msg: String) : Luposdate3000Exception(classname, msg)
public class DatasetImportFailedException(file: String) : EvaluationException("DatasetImportFailedException", "importing the dataset '$file' failed")
public class IncompatibleTypesDuringCompareException : EvaluationException("IncompatibleTypesDuringCompareException", "The provided types are incompatible.")
public class CanNotCastBNodeToDoubleException : EvaluationException("CanNotCastBNodeToDoubleException", "Can not cast BNode to Double.")
public class CanNotCastBNodeToDecimalException : EvaluationException("CanNotCastBNodeToDecimalException", "Can not cast BNode to Decimal.")
public class CanNotCastBNodeToIntException : EvaluationException("CanNotCastBNodeToIntException", "Can not cast BNode to Int.")
public class CanNotCastBNodeToBooleanException : EvaluationException("CanNotCastBNodeToBooleanException", "Can not cast BNode to Boolean.")
public class CanNotCastBooleanToDoubleException : EvaluationException("CanNotCastBooleanToDoubleException", "Can not cast Boolean to Double.")
public class CanNotCastBooleanToDecimalException : EvaluationException("CanNotCastBooleanToDecimalException", "Can not cast Boolean to Decimal.")
public class CanNotCastBooleanToIntException : EvaluationException("CanNotCastBooleanToIntException", "Can not cast Boolean to Int.")
public class CanNotCastUndefToDoubleException : EvaluationException("CanNotCastUndefToDoubleException", "Can not cast Undef to Double.")
public class CanNotCastUndefToDecimalException : EvaluationException("CanNotCastUndefToDecimalException", "Can not cast Undef to Decimal.")
public class CanNotCastUndefToIntException : EvaluationException("CanNotCastUndefToIntException", "Can not cast Undef to Int.")
public class CanNotCastUndefToBooleanException : EvaluationException("CanNotCastUndefToBooleanException", "Can not cast Undef to Boolean.")
public class CanNotCastErrorToDoubleException : EvaluationException("CanNotCastErrorToDoubleException", "Can not cast Error to Double.")
public class CanNotCastErrorToDecimalException : EvaluationException("CanNotCastErrorToDecimalException", "Can not cast Error to Decimal.")
public class CanNotCastErrorToIntException : EvaluationException("CanNotCastErrorToIntException", "Can not cast Error to Int.")
public class CanNotCastErrorToBooleanException : EvaluationException("CanNotCastErrorToBooleanException", "Can not cast Error to Boolean.")
public class CanNotCastIriToDoubleException : EvaluationException("CanNotCastIriToDoubleException", "Can not cast Iri to Double.")
public class CanNotCastIriToDecimalException : EvaluationException("CanNotCastIriToDecimalException", "Can not cast Iri to Decimal.")
public class CanNotCastIriToIntException : EvaluationException("CanNotCastIriToIntException", "Can not cast Iri to Int.")
public class CanNotCastIriToBooleanException : EvaluationException("CanNotCastIriToBooleanException", "Can not cast Iri to Boolean.")
public class CanNotCastDateTimeToDoubleException : EvaluationException("CanNotCastDateTimeToDoubleException", "Can not cast DateTime to Double.")
public class CanNotCastDateTimeToDecimalException : EvaluationException("CanNotCastDateTimeToDecimalException", "Can not cast DateTime to Decimal.")
public class CanNotCastDateTimeToIntException : EvaluationException("CanNotCastDateTimeToIntException", "Can not cast DateTime to Int.")
public class CanNotCastDateTimeToBooleanException : EvaluationException("CanNotCastDateTimeToBooleanException", "Can not cast DateTime to Boolean.")
public class CanNotCastLiteralToDoubleException : EvaluationException("CanNotCastLiteralToDoubleException", "Can not cast Literal to Double.")
public class CanNotCastLiteralToDecimalException : EvaluationException("CanNotCastLiteralToDecimalException", "Can not cast Literal to Decimal.")
public class CanNotCastLiteralToIntException : EvaluationException("CanNotCastLiteralToIntException", "Can not cast Literal to Int.")
public class UnknownOperatorTypeInXMLException(type: String) : EvaluationException("UnknownOperatorTypeInXMLException", "Unknown type '$type' during parsing xml file.")
public class UnknownDataFileException(filename: String) : EvaluationException("UnknownDataFileException", "Unknown filetype '$filename' during parsing to xml.")
public class EnpointRecievedInvalidPath(path: String) : EvaluationException("EnpointRecievedInvalidPath", "There was a not recognized request with path '$path'.")
public class GraphNameAlreadyExistsDuringCreateException(name: String) : EvaluationException("GraphNameAlreadyExistsDuringCreateException", "The graph '$name' already exists before creation.")
public class GraphNameNotExistsDuringDeleteException(name: String) : EvaluationException("GraphNameNotExistsDuringDeleteException", "The graph '$name' did not exist before deletion.")
public class GraphNameNotFoundException(name: String) : EvaluationException("GraphNameNotFoundException", "The graph '$name' does not exist.")
public class UnreachableException : EvaluationException("UnreachableException", "This should be unreachable.")
public class EmptyResultException : EvaluationException("EmptyResultException", "")
// known bugs --->>>
public class BugException(classname: String, bugname: String) : Luposdate3000Exception("BugException", "class '$classname' has bug '$bugname'.")
// used to indicate, that intentionally every exception is caught here
public typealias DontCareWhichException = Throwable
public class JenaBugException(bugname: String) : Luposdate3000Exception("JenaBugException", "Jena has bug: '$bugname'")
