/*
 * This file is part of the Luposdate3000 distribution (https://github.com/luposdate3000/luposdate3000).
 * Copyright (c) 2020-2021, Institute of Information Systems (Benjamin Warnke and contributors of LUPOSDATE3000), University of Luebeck
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, version 3.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
package lupos.test
internal object SparqlTestSuiteConverterToUnitTestIgnoreListDueToBugsInSimulator {
    internal val ignoreListDueToBugsInSimulator = mapOf(
        "HOURS" to "distributed dictionary access",
        "MD5overUnicodedata" to "distributed dictionary access",
        "bind11BINDscopingVariableinfilterinscope" to "distributed dictionary access",
        "ADD1" to "query not distributed",
        "INSERT01" to "query not distributed",
        "MIN" to "distributed dictionary access",
        "MONTH" to "distributed dictionary access",
        "MOVE6" to "query not distributed",
        "STRLEN" to "distributed dictionary access",
        "ADD3" to "query not distributed",
        "FLOOR" to "distributed dictionary access",
        "INSERT03" to "query not distributed",
        "COUNT8b" to "distributed dictionary access",
        "ADD6" to "query not distributed",
        "MINUTES" to "distributed dictionary access",
        "ADDSILENT" to "query not distributed",
        "COPY1" to "query not distributed",
        "SHA1" to "distributed dictionary access",
        "ADD7" to "query not distributed",
        "Expressionhasundefinedvariable" to "distributed dictionary access",
        "MOVE3" to "query not distributed",
        "SECONDS" to "distributed dictionary access",
        "ADD2" to "query not distributed",
        "CEIL" to "distributed dictionary access",
        "COPY3" to "query not distributed",
        "Expressionisequality" to "distributed dictionary access",
        "SHA256" to "distributed dictionary access",
        "SimpleDELETE3" to "query not distributed",
        "ADD4" to "query not distributed",
        "COPY6" to "query not distributed",
        "INSERT04" to "query not distributed",
        "ROUND" to "distributed dictionary access",
        "INSERTUSING01" to "query not distributed",
        "MOVE1" to "query not distributed",
        "Reuseaprojectexpressionvariableinorderby" to "distributed dictionary access",
        "DAY" to "distributed dictionary access",
        "LCASE" to "distributed dictionary access",
        "UCASE" to "distributed dictionary access",
        "YEAR" to "distributed dictionary access",
        "SAMPLE" to "distributed dictionary access",
        "COPYSILENT" to "query not distributed",
        "SimpleDELETEWHERE3" to "query not distributed",
        "Group1" to "distributed dictionary access",
        "STRDTSTR" to "distributed dictionary access",
        "constructwhere02CONSTRUCTWHERE" to "query not distributed",
        "MD5" to "distributed dictionary access",
        "MOVESILENT" to "query not distributed",
        "STRLANGSTR" to "distributed dictionary access",
        "bind10BINDscopingVariableinfilternotinscope" to "distributed dictionary access",

        "bind01BIND" to "distributed dictionary access",
        "bind03BIND" to "distributed dictionary access",
        "CLEARGRAPH" to "distributed dictionary access",
        "CLEARNAMED" to "distributed dictionary access",
        "CONCAT" to "distributed dictionary access",
        "COPY7" to "distributed dictionary access",
        "COUNT3" to "distributed dictionary access",
        "DEntailmenttesttoshowthatneitherliteralsinsubjectpositionnornewlyintroducedsurrogateblanknodesaretobereturnedinqueryanswers" to "distributed dictionary access",
        "IF" to "distributed dictionary access",
        "RDFinferencetestluposDuplicate1" to "distributed dictionary access",
        "RDFSinferencetesttoshowthatneitherliteralsinsubjectpositionnornewlyintroducedsurrogateblanknodesaretobereturnedinqueryanswers" to "distributed dictionary access",
        "resourcesbtc020sparql80" to "distributed dictionary access",
        "resourcesmyqueriesoptional10sparql5" to "distributed dictionary access",
        "resourcesmyqueriesoptional13sparql4" to "distributed dictionary access",
        "resourcesmyqueriesoptional13sparql5" to "distributed dictionary access",
        "resourcesmyqueriesoptional16sparql5" to "distributed dictionary access",
        "resourcesmyqueriesoptional17sparql4" to "distributed dictionary access",
        "resourcesmyqueriesoptional17sparql5" to "distributed dictionary access",
        "resourcesmyqueriesoptional21sparql4" to "distributed dictionary access",
        "resourcesmyqueriesoptional23sparql4" to "distributed dictionary access",
        "resourcesmyqueriesoptional23sparql5" to "distributed dictionary access",
        "resourcesmyqueriesoptional24sparql4" to "distributed dictionary access",
        "resourcesmyqueriesoptional25sparql4" to "distributed dictionary access",
        "resourcesmyqueriesoptional27sparql5" to "distributed dictionary access",
        "resourcesmyqueriesoptional28sparql4" to "distributed dictionary access",
        "resourcesmyqueriesoptional33sparql5" to "distributed dictionary access",
        "resourcesmyqueriesoptional36sparql5" to "distributed dictionary access",
        "resourcesmyqueriesoptional40sparql4" to "distributed dictionary access",
        "resourcesmyqueriesoptional43sparql4" to "distributed dictionary access",
        "resourcesmyqueriesoptional51sparql5" to "distributed dictionary access",
        "resourcesmyqueriesoptional54sparql5" to "distributed dictionary access",
        "resourcesmyqueriesoptional58sparql5" to "distributed dictionary access",
        "resourcesmyqueriesoptional5sparql4" to "distributed dictionary access",
        "resourcesmyqueriesoptional5sparql5" to "distributed dictionary access",
        "resourcesmyqueriesoptional6sparql5" to "distributed dictionary access",
        "resourcessp2bq10sparql700" to "distributed dictionary access",
        "resourcessp2bq111sparql973" to "distributed dictionary access",
        "resourcessp2bq12a1sparql700" to "distributed dictionary access",
        "resourcessp2bq12b1sparql700" to "distributed dictionary access",
        "resourcessp2bq1sparql247" to "distributed dictionary access",
        "resourcessp2bq3asparql21" to "distributed dictionary access",
        "resourcessp2bq3bsparql247" to "distributed dictionary access",
        "resourcessp2bq4sparql973" to "distributed dictionary access",
        "resourcessp2bq5asparql21" to "distributed dictionary access",
        "resourcessp2bq5bsparql973" to "distributed dictionary access",
        "resourcessp2bq61sparql21" to "distributed dictionary access",
        "resourcessp2bq62sparql21" to "distributed dictionary access",
        "resourcessp2bq65sparql247" to "distributed dictionary access",
        "resourcessp2bq65sparql700" to "distributed dictionary access",
        "resourcessp2bq6sparql247" to "distributed dictionary access",
        "resourcessp2bq7sparql700" to "distributed dictionary access",
        "resourcessp2bq91sparql21" to "distributed dictionary access",
        "Simpleinsertdata1" to "distributed dictionary access",
        "simpletriplepatternmatch" to "distributed dictionary access",
        "sparqldl01rqtriplepattern" to "distributed dictionary access",
        "STRENDS" to "distributed dictionary access",
        "SUMwithGROUPBY" to "distributed dictionary access",
        "tsv01TSVResultFormat" to "distributed dictionary access",

    )
}
