#Scalable Join Processing on Very Large RDF Graphs
prefix uni: <http://purl.uniprot.org/core/>
prefix uniprot: <http://purl.uniprot.org/>
prefix schema: <http://www.w3.org/2000/01/rdf-schema#>
prefix file: <file:///uniprot.rdf#_>
select ?a ?vo where {
 ?a uni:encodedBy ?vo .
 ?a schema:seeAlso uniprot:refseq/NP_346136.1 .
 ?a schema:seeAlso uniprot:tigr/SP_1698 .
 ?a uni:memberOf uniprot:uniref/UniRef100_Q04J74 .
 ?a schema:seeAlso uniprot:pfam/PF00842 .
 ?a schema:seeAlso uniprot:prints/PR00992 .
 ?b uni:annotation file:58FFF .
 ?b uni:sequence uniprot:isoforms/P0A2W9-1 .
 ?b uni:replaces uniprot:uniprot/Q54899 .
 ?b uni:modified "2008-07-22" .
 ?b a uni:Protein .
 ?a uni:replaces ?ab .
 ?ab uni:replacedBy ?b .
}

