#Parallelizing Join Computations of SPARQL Queries for Large Semantic Web Databases
select * where {
 ?m <http://purl.org/dc/elements/1.1/title> ?t .
 ?x <http://xmlns.com/foaf/0.1/made> ?m .
 ?x <http://xmlns.com/foaf/0.1/nick> ?i .
}
