#Parallelizing Join Computations of SPARQL Queries for Large Semantic Web Databases
select * where {
 ?x <http://www.w3.org/2005/Atomuri> ?u .
 ?x <http://www.w3.org/2005/Atomname> ?n .
 ?y <http://www.w3.org/2005/Atomname> ?n .
 ?y <http://www.w3.org/2005/Atomemail> ?m .
}
