#Parallelizing Join Computations of SPARQL Queries for Large Semantic Web Databases --- BTC 2009
select * where {
 ?x <http://www.geonames.org/ontology#name> ?n1 .
 ?x <http://www.w3.org/2003/01/geo/wgs84_pos#lat> ?l .
 ?x <http://www.geonames.org/ontology#inCountry> <http://www.geonames.org/countries/#DE> .
 ?y <http://www.geonames.org/ontology#name> ?n2 .
 ?y <http://www.w3.org/2003/01/geo/wgs84_pos#lat> ?l .
 ?y <http://www.geonames.org/ontology#inCountry> <http://www.geonames.org/countries/#DE> .
}
